lesson_group 'lessonGroup-2', display_name: 'Content'
lesson 'translation missing: en-US.data.script.name.coursea-2020-new.lessons.translation missing: en-US.data.script.name.coursea-2020-new.lessons.Safety in My Online Neighborhood.name.name', display_name: 'translation missing: en-US.data.script.name.coursea-2020-new.lessons.translation missing: en-US.data.script.name.coursea-2020-new.lessons.Safety in My Online Neighborhood.name.name'

