hidden false
teacher_resources [["lessonPlans", "/link/to/lesson/plans"], ["teacherForum", "https://forum.code.org/"]]
version_year '2021'
curriculum_umbrella 'CSF'

lesson_group 'lessonGroup-3', display_name: 'Loops'
lesson 'lesson-6', display_name: 'Loops in Ice Age'

lesson 'lesson-7', display_name: 'Drawing Shapes with Loops'

lesson 'lesson-8', display_name: 'Nested Loops in Maze'

lesson_group 'lessonGroup-2', display_name: 'Conditionals'
lesson 'lesson-1', display_name: 'Conditionals with Cards'

lesson 'lesson-2', display_name: 'If/Else with Bee'

lesson 'lesson-3', display_name: 'While Loops in Farmer'

lesson 'lesson-4', display_name: 'Until Loops in Maze'

lesson 'lesson-5', display_name: 'Harvesting with Conditionals'

lesson_group 'lessonGroup-4', display_name: 'Binary'
lesson 'lesson-9', display_name: 'Binary Images'

lesson 'lesson-10', display_name: 'Binary Images with Artist'

